"use client";
import Header from '@/components/Header';
import './globals.css';
// import localFont from 'next/font/local';

// const myFont = localFont({ src: "./gotham-book-webfont.woff2", variable: "--font" })

export const metadata = {
  title: 'Gordswork',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className={`font-Gotham bg-gradient-to-r from-violet-900 to-black text-white h-screen snap-y overflow-x-hidden max-w-screen snap-mandatory overflow-y-scroll z-0`}>
          <Header />
          {children}
        </div>
      </body>
    </html>
  )
}
